Controllers/RequestFormsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ataa.Data;
using Ataa.Models;
using System.Dynamic;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using System.Globalization;
using Microsoft.AspNetCore.Authorization;

namespace Ataa.Views
{
    [Authorize(Roles = "User")]

    public class RequestFormsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RequestFormsController(ApplicationDbContext context)
        {
            _context = context;
        }
      
        // GET: RequestForms
        public async Task<IActionResult> Index()
        {
            dynamic mymodel = new ExpandoObject();
            mymodel.Request = await _context.RequestForm.ToListAsync();
            mymodel.User = await _context.User.ToListAsync();
            var RequestUser = from r in _context.RequestForm
                              join u in _context.User on r.UserId equals u.Id into ru
                              from u in ru.DefaultIfEmpty()
                              select new RequestUser { ReqForm = r, user=u};
            RequestUser = RequestUser.Where(r => r.ReqForm.UserId != User.FindFirst(ClaimTypes.NameIdentifier).Value && (r.ReqForm.StatusId == 2 || r.ReqForm.StatusId == 5));
            ViewBag.haveServices = true;

            if (RequestUser.ToArray().Length == 0)
            {
                ViewBag.haveServices = false;
            }
            Status();                     
            return View(RequestUser);
        }
        public async Task<IActionResult> MyServices()
        {
            dynamic mymodel = new ExpandoObject();
            mymodel.Request = await _context.RequestForm.ToListAsync();
            mymodel.Status = await _context.Status.ToListAsync();
            var RequestStatus = from r in _context.RequestForm
                                join s in _context.Status on r.StatusId equals s.Id into rs
                                from s in rs.DefaultIfEmpty()
                                select new RequestStatus { reqForm = r, status = s };
            ViewData["Requests"] = RequestStatus.Count();

            var Users = from u in _context.User
                        select u;
            RequestStatus = RequestStatus.Where(r => r.reqForm.UserId == User.FindFirst(ClaimTypes.NameIdentifier).Value);
            Status();
            return View(RequestStatus);
        }

        public async void Status()
        {
            string date = DateTime.Now.GetDateTimeFormats('d')[0];
            string time = DateTime.Now.GetDateTimeFormats('t')[0];

           
                var request = from m in _context.RequestForm
                        select m;
                var ids = request.Select(b => b.Id);

                foreach (var id in ids)
                {
                    var isMeetDateP = false;
                    var isMeetDateTimeD = false;

                    var r = request.Where(fi => fi.Id == id);
                    var r1 = r.First();
                    var servSDate = r1.StartDate.GetDateTimeFormats('d')[0];
                    var servEDate = r1.EndDate.GetDateTimeFormats('d')[0];
                    var servSTime = r1.StartTime.GetDateTimeFormats('t')[0];
                    var servETime = r1.EndTime.GetDateTimeFormats('t')[0];
                    var sta = r1.StatusId;


                    if (sta == 2 || sta == 5)
                    {
                        if ((DateTime.Parse(date, CultureInfo.InvariantCulture) >= (DateTime.Parse(servSDate, CultureInfo.InvariantCulture))) && (DateTime.Parse(date, CultureInfo.InvariantCulture) < (DateTime.Parse(servEDate, CultureInfo.InvariantCulture))))
                        {
                        if ((DateTime.Parse(time) >= DateTime.Parse(servSTime)) && (DateTime.Parse(time) <= DateTime.Parse(servETime)))
                        {
                            isMeetDateP = true;
                        }
                        }

                        else if ((DateTime.Parse(date, CultureInfo.InvariantCulture) == (DateTime.Parse(servEDate, CultureInfo.InvariantCulture))))
                        {
                            if ((DateTime.Parse(time) >= DateTime.Parse(servSTime)) && (DateTime.Parse(time) <= DateTime.Parse(servETime)))
                            {
                                isMeetDateP = true;
                            }
                            else if((DateTime.Parse(time) > DateTime.Parse(servETime)))
                            {
                            isMeetDateTimeD = true;
                            }
                        }
                        else
                        {
                            if (DateTime.Parse(date) > DateTime.Parse(servEDate))
                            {
                                isMeetDateTimeD = true;
                            }
                            
                        }
                    }
                    if (isMeetDateP)
                    {
                        r1.StatusId = 5;
                    }
                    if (isMeetDateTimeD)
                    {
                        r1.StatusId = 4;
                    }
                }
                _context.SaveChanges();
                await _context.SaveChangesAsync();
            

          
        }
        public async Task<IActionResult> MyRequests()
        {
            dynamic mymodel = new ExpandoObject();
            mymodel.Request = await _context.RequestForm.ToListAsync();
            mymodel.Status = await _context.Status.ToListAsync();
            var RequestStatus = from r in _context.RequestForm
                                join s in _context.Status on r.StatusId equals s.Id into rs
                                from s in rs.DefaultIfEmpty()
                                select new RequestStatus { reqForm = r, status = s };
            ViewData["Requests"] = RequestStatus.Count();

            var Users = from u in _context.User
                        select u;
            RequestStatus = RequestStatus.Where(r => r.reqForm.UserId == User.FindFirst(ClaimTypes.NameIdentifier).Value);

            Status();

            return View(RequestStatus);
        }


        // GET: RequestForms/Details/5
        public async Task<IActionResult> SDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var requestForm = await _context.RequestForm
                .FirstOrDefaultAsync(m => m.Id == id);

                    
            if (requestForm == null)
            {
                return NotFound();
            }
            var re = _context.Attendancelist.Where(re => re.FormId == id);
            ViewBag.AttCount = re.Count();

            return View(requestForm);
        }
        public async Task<IActionResult> RDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var requestForm = await _context.RequestForm
                .FirstOrDefaultAsync(m => m.Id == id);


            if (requestForm == null)
            {
                return NotFound();
            }
            var re = _context.Attendancelist.Where(re => re.FormId == id);
            ViewBag.AttCount = re.Count();

            return View(requestForm);
        }


        public async Task<IActionResult> Grantees(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            dynamic mymodell = new ExpandoObject();
            mymodell.at = await _context.Attendancelist.ToListAsync();
            mymodell.us = await _context.User.ToListAsync();

            var usersatt = from a in _context.Attendancelist
                           join u in _context.User on a.UserId equals u.Id into au
                           from u in au.DefaultIfEmpty()
                           select new AttendUser { attlist = a, user = u };
            var attendance = usersatt.Where(m => m.attlist.FormId == id);
            

            if (attendance.ToArray().Length > 0)
            {
                var idf = attendance.First(n => n.attlist.FormId == id);
            }
            ViewBag.formId = id;

            return View(attendance);
        }


        public IActionResult Apply(int id)
        {
            ViewBag.isApplied = true;

            Attendancelist model = new Attendancelist();
            if (ModelState.IsValid)
            {
                var atReq = _context.Attendancelist.Where(r => r.FormId == id && r.UserId == User.FindFirst(ClaimTypes.NameIdentifier).Value);
                var atReqCount = atReq.Count();

                var req = _context.RequestForm.First(requ => requ.Id == id);
                var nOfGrantees = req.NumberOfGrantee;
                var re = _context.Attendancelist.Where(re => re.FormId == id);
                var AttCount = re.Count();
                if (atReqCount == 0 && AttCount <= nOfGrantees)
                {
                    model.UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                    model.FormId = id;
                    _context.Add(model);

                    _context.SaveChanges();
                }
                ViewBag.isApplied = false;
            }
            return Redirect("https://localhost:44395/RequestForms/ServiceDetails/"+ id.ToString());
        }

        public async Task<IActionResult> ServiceDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
          

            var users = from u in _context.User
                        select u;

            var v = await _context.RequestForm.FirstOrDefaultAsync(m => m.Id == id);

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - Ataa</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />



    <!---->
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="fonts/iconic/css/material-design-iconic-font.min.css">
    <!--===============================================================================================-->
    <!-- Favicons -->
    <link rel="icon" type="~/image/png" href="~/images/ataaicon.png" />

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link rel="stylesheet" type="text/css" href="~/assets/css/style.css">


    <link rel="stylesheet" type="text/css" href="~/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/css/main.css">
    <link rel="stylesheet" type="text/css" href="~/css/site.css">


</head>



<body oncontextmenu='return false' class='snippet-body'>
    <!-- ======= Top Bar ======= -->
    <section id="topbar" class="d-flex align-items-center">
        <div class="container d-flex justify-content-center justify-content-md-between">
            <div class="contact-info d-flex align-items-center">
                <i class="bi bi-envelope-fill"></i><a href="mailto:mahmoudalaishat1@gmail.com">mahmoudalaishat1@gmail.com</a>
                <i class="bi bi-phone-fill phone-icon"></i> +962 781674722
            </div>
            <div class="social-links d-none d-md-block">
                <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                <a href="https://www.linkedin.com/in/mahmoud-alaishat-43a1a6204" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
            </div>
        </div>
    </section>
    <header id="header" class="d-flex align-items-center">
        <div class="container d-flex align-items-center">

            @*<h1 class="logo me-auto"><a href="index.html">ATAA</a></h1>*@
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
            <img style="width:90px;height:90px;" src="~/images/ataaicon.png" alt="" class="d-inline" /> <h1 class="logo me-auto"><a href="index.html">ATAA</a></h1>

            <nav id="navbar" class="navbar">

                <ul>
                    <li><a class="nav-link scrollto active" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a class="nav-link scrollto" href="#about">About</a></li>
                    <li><a class="nav-link scrollto" href="#services">Services</a></li>
                    <li><a class="nav-link scrollto" href="#team">Team</a></li>

                    <li class="dropdown">
                        <a href="#"><span>Sectors</span> <i class="bi bi-chevron-down"></i></a>
                        <ul>
                            <li><a href="#">Health</a></li>
                            <li class="dropdown">
                                <a href="#"><span>Education</span> <i class="bi bi-chevron-right"></i></a>
                                <ul>
                                    <li><a href="#">Schools</a></li>
                                    <li><a href="#">Universities</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Agriculture</a></li>
                            <li><a href="#">Entertainment</a></li>
                            <li><a href="#">Transportation</a></li>
                            <li><a href="#">Commerce</a></li>

                        </ul>
                    </li>

                    <li><a class="nav-link scrollto" href="#contact" style="margin-right:30px">Contact</a></li>

                    @{
                        if (SignInManager.IsSignedIn(User) && User.IsInRole("User"))
                        {

                            <li><a class="nav-link scrollto getstarted" asp-area="" asp-controller="RequestForms" asp-action="Index">My Space</a></li>
                        }
                        else if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li><a class="nav-link scrollto getstarted" asp-area="" asp-controller="Admin" asp-action="Index">Dashboard</a></li>
                        }
                    }
                    <partial name="_LoginPartial" />
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>

            </nav>
        </div>
    </header>
    <div class="container-fluid p-0">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer id="footer" style="background-color: #449d5b">
        <div class="container">
                <img style="width:190px;height:180px;" src="~/images/ataalooo.png" alt="" class="logo d-inline rounded-circle mb-2" />
            <p style="color:white">Where You Don't Need To Be Rich To Be Able To Give</p>
            <div class="social-links">
                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                <a href="https://www.linkedin.com/in/mahmoud-alaishat-43a1a6204" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
            <div class="copyright">
                <i class="bi bi-battery-charging"></i> Powered  By <strong><span>Mahmoud Alaishat</span></strong>
            </div>
        </div>
    </footer>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!--===============================================================================================-->
    <script src="vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="vendor/animsition/js/animsition.min.js"></script>
    <!--===============================================================================================-->
    <script src="vendor/bootstrap/js/popper.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="vendor/daterangepicker/moment.min.js"></script>
    <script src="vendor/daterangepicker/daterangepicker.js"></script>
    <!--===============================================================================================-->
    <script src="vendor/countdowntime/countdowntime.js"></script>
    <!--===============================================================================================-->
    <script src="js/main.js"></script>
    <script type='text/javascript' src='https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js'></script>
    <script type='text/javascript'></script>
    <!-- Vendor JS Files -->
    <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="assets/vendor/php-email-form/validate.js"></script>
    <script src="assets/vendor/swiper/swiper-bundle.min.js"></script>

    <!-- Template Main JS File -->
    <script src="assets/js/main.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout2.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"]</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- plugins:css -->
    <link rel="stylesheet" href="~/assets1/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/assets1/vendors/css/vendor.bundle.base.css">
    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">



    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="~/assets1/css/style.css">
    <!-- End layout styles -->
    <!-- Template Main CSS File -->
    <link rel="stylesheet" type="text/css" href="~/assets/css/style.css">

    <link rel="shortcut icon" href="~/assets/img/ataaicon.png" />
    <style>
        .container-scroller .page-body-wrapper .sidebar .nav .nav-item .nav-link .menu-title {
            display: inline-block;
            font-size: 0.875rem;
            line-height: 1;
            vertical-align: middle;
            color: #4cb568;
            font-family: "ubuntu-medium", sans-serif;
        }

        .sidebar .nav .nav-item .nav-link i.menu-icon {
            font-size: 1.125rem;
            line-height: 1;
            margin-left: auto;
            color: #4cb568;
        }

        #navbar ul li a {
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
            font-size: 17px
        }
    </style>
</head>

<body>
    <header id="header" class="d-flex align-items-center">
        <div class="container-fluid d-flex align-items-center">

            @*<h1 style="margin-left:60px" class="logo me-auto"><a href="index.html">ATAA</a></h1>*@
            <!-- Uncomment below if you prefer to use an image logo -->
                <img style="width:90px;height:90px;" src="~/images/ataaicon.png" alt="" class="logo d-inline ml-3"/> <h1  class="logo me-auto"><a href="index.html">ATAA</a></h1>
            <nav id="navbar" class="navbar">

                <ul>
                    @*<li><a class="nav-link scrollto active" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>*@

                    @*<li style="margin-right:70px" class="dropdown">
            <a href="#"><span>Test Unit</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
                <li><a href="#">Drop Down 1</a></li>
                <li class="dropdown">
                    <a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                    <ul>
                        <li><a href="#">Deep Drop Down 1</a></li>
                        <li><a href="#">Deep Drop Down 2</a></li>
                        <li><a href="#">Deep Drop Down 3</a></li>
                        <li><a href="#">Deep Drop Down 4</a></li>
                        <li><a href="#">Deep Drop Down 5</a></li>
                    </ul>
                </li>
                <li><a href="#">Drop Down 2</a></li>
                <li><a href="#">Drop Down 3</a></li>
                <li><a href="#">Drop Down 4</a></li>
            </ul>
        </li>*@


                    <partial name="_LoginPartial" />
                    <a class="nav-link">
                        <i class="mdi mdi-fullscreen ml-5" id="fullscreen-button"></i>
                    </a>
                </ul>
                

                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                    <span class="mdi mdi-menu"></span>
                </button>
            </nav>
        </div>
    </header>


    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper">
            <nav class="sidebar sidebar-offcanvas rounded-3" id="sidebar">
                <ul class="nav">
                    <li class="nav-item nav-profile">
                        <a class="nav-link" asp-controller="RequestForms" asp-action="Profile">
                            <div class="nav-profile-image">
                                <img src="~/assets/img/team/team-1.png" alt="profile">
                                <span class="login-status online"></span>
                                <!--change to offline or busy as needed-->
                            </div>
                            <div class="nav-profile-text d-flex flex-column">
                                <span class="font-weight-bold mb-2">@User.Identity.Name</span>
                                <span class="text-secondary text-small">CEO</span>
                            </div>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="RequestForms" asp-action="Index">
                            <span class="menu-title">Home</span>
                            <i class="mdi mdi-home menu-icon"></i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="RequestForms" asp-action="MyServices">
                            <span class="menu-title">My Services</span>
                            <i class="mdi mdi-star-four-points menu-icon"></i>

                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">
                            <span class="menu-title">Settings</span>
                            <i class="mdi mdi-settings-outline menu-icon"></i>
                        </a>
                    </li>
                    <h6 class="font-weight-bold mt-5 w-100 ml-3 text-muted">Requests</h6>
                    <div class="border-bottom"></div>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="RequestForms" asp-action="MyRequests">
                            <span class="menu-title">My Requests</span>
                            <i class="mdi mdi-format-list-bulleted menu-icon menu-icon"></i>
                        </a>
                    </li>
                    <a asp-action="Create" class="btn btn-success col-10 mt-3 mb-2 pt-3 pb-3 ml-4">+ Add New Service</a>




                    <div class="border-bottom mb-2"></div>
                    <li class="nav-item">
                        <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                            <button style="border-color:white" type="submit" class="btn btn-danger col-9 ml-4 p-3"><i class="mdi mdi-logout"></i> Logout</button>
                        </form>
                    </li>
                </ul>
            </nav>
            <div class="main-panel">
                <div class="content-wrapper" style="background: linear-gradient(183deg, rgba(114,239,146,1) 0%, rgba(94,207,168,1) 44%, rgba(100,223,133,1) 100%);
    padding: 2.0rem 2.0rem; width: 100%; -webkit-box-flex: 1; -ms-flex-positive: 1; flex-grow: 1;">
                    <div class="page-header">
                        <h3 class="page-title text-white">
                            <span style="background-color: #68d987 " class="page-title-icon  text-white mr-2">
                                <i class="mdi mdi-home"></i>
                            </span> @ViewData["Title"]
                        </h3>
                    </div>
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
    <script src="lib/jquery/dist/jquery.min.js"></script>
    <script src="vendor/jquery/jquery-3.2.1.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <!-- plugins:js -->
    <script src="assets1/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="assets1/vendors/chart.js/Chart.min.js"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="assets1/js/off-canvas.js"></script>
    <script src="assets1/js/hoverable-collapse.js"></script>
    <script src="assets1/js/misc.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="assets1/js/dashboard.js"></script>
    <script src="assets1/js/todolist.js"></script>
    <!-- End custom js for this page -->

    @RenderSection("Scripts", required: false)
</body>
</html>